# -*- coding: utf-8 -*-
"""random_forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17hbwByRUL4zpZDlc9RIJMyl12I2_sgMu
"""

! gdown --id 1TbaCadGKoN6PBrrfZ54tkbjFlEAUI4a9



from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

df = pd.read_csv('no_index_clean_avg_all.csv')
df.dropna()

labels = np.array(df['avgAGC'])
df.index = df['time']
features = df.drop(['time', 'avgAGC', 'lat', 'lon', 'avgBAF'], axis=1)
feature_list = list(features.columns)
features = np.array(features)

train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25)

rf = RandomForestRegressor(n_estimators= 100)
rf.fit(train_features, train_labels)
predictions = rf.predict(test_features)
print(test_labels)
errors = abs(predictions - test_labels)
print('Mean Absolute Error:', round(np.mean(errors), 4), 'AGC')

from sklearn.metrics import r2_score, accuracy_score, precision_score
r2 = r2_score(test_labels, predictions)
print(r2)

mape = 100 * (errors / test_labels)

accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

# Get numerical feature importances
importances = list(rf.feature_importances_)

# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]

# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)

# Print out the feature and importances
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances]


import matplotlib.pyplot as plt

#get_ipython().run_line_magic('matplotlib', 'inline')

# list of x locations for plotting
x_values = list(range(len(importances)))

# Make a bar chart
plt.bar(x_values, importances, orientation = 'vertical')

# Tick labels for x axis
plt.xticks(x_values, feature_list, rotation='vertical')

# Axis labels and title
plt.ylabel('Importance'); plt.xlabel('Variable'); plt.title('Variable Importances')

plt.show()



from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np



df = pd.read_csv('no_index_clean_avg_all.csv')
df.dropna()

labels = np.array(df['avgAGC'])
df.index = df['time']
features = df.drop(['time', 'avgAGC', 'lat', 'lon', 'avgCFC'], axis=1)

scaledFeatures = StandardScaler().fit_transform(features.values)

features = pd.DataFrame(scaledFeatures, index=features.index, columns = features.columns)

feature_list = list(features.columns)
features = np.array(features)

train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25)

rf = RandomForestRegressor(n_estimators = 50)
rf.fit(train_features, train_labels)
predictions = rf.predict(test_features)
print(test_labels)
errors = abs(predictions - test_labels)
print('Mean Absolute Error:', round(np.mean(errors), 4), 'AGC')

from sklearn.metrics import r2_score, accuracy_score, precision_score
r2 = r2_score(test_labels, predictions)
print(f'R2 Score: {r2}')

#mape = 100 * (errors / test_labels)

#accuracy = 100 - np.mean(mape)
#print('Accuracy:', round(accuracy, 2), '%.')

# Get numerical feature importances
importances = list(rf.feature_importances_)

# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]

# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)

# Print out the feature and importances
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances]


import matplotlib.pyplot as plt

#get_ipython().run_line_magic('matplotlib', 'inline')

# list of x locations for plotting
x_values = list(range(len(importances)))

# Make a bar chart
plt.bar(x_values, importances, orientation = 'vertical')

# Tick labels for x axis
plt.xticks(x_values, feature_list, rotation='vertical')

# Axis labels and title
plt.ylabel('Importance'); plt.xlabel('Variable'); plt.title('Variable Importances')

plt.show()

errors.shape

from sklearn.tree import export_graphviz

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import export_text
from sklearn.datasets import load_iris

# Visualise classical Confusion M0atrix
from sklearn.metrics import confusion_matrix
CM = confusion_matrix(labels, predictions)
print(conf_mat)

# Visualize it as a heatmap
import seaborn
seaborn.heatmap(CM)
plt.show()